project_id = "ymffclntmynwfdiarlaw"

[functions.register-account]
verify_jwt = false

[functions.activate-plan]
verify_jwt = true

[functions.create-plan-charge]
verify_jwt = true

[functions.asaas-webhook]
verify_jwt = false

[functions.desktop-download]
verify_jwt = true

[functions.track-access]
verify_jwt = false

[functions.manage-operators]
verify_jwt = false

[functions.operator-login]
verify_jwt = false
