// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createAdaptiveStorage } from '../../../../shared/security/browserStorage';
import { createKeepConnectedReader } from '../../../../shared/security/authPersistence';
import { cleanupLegacySupabaseAuthStorage } from '../../../../shared/security/supabaseAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const shouldPersistSiteSession = createKeepConnectedReader('happycash:site:keep-connected', false);
const SITE_AUTH_STORAGE_KEY = 'happycash:site:auth';

cleanupLegacySupabaseAuthStorage(SITE_AUTH_STORAGE_KEY);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createAdaptiveStorage(shouldPersistSiteSession),
    persistSession: true,
    autoRefreshToken: true,
    storageKey: SITE_AUTH_STORAGE_KEY,
  }
});
