// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createAdaptiveStorage } from '../../../../shared/security/browserStorage';
import { createKeepConnectedReader } from '../../../../shared/security/authPersistence';
import { cleanupLegacySupabaseAuthStorage } from '../../../../shared/security/supabaseAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const AGENDA_AUTH_STORAGE_KEY = 'happycash:agenda:auth';
const shouldPersistAgendaSession = createKeepConnectedReader('happycash:agenda:keep-connected', false);

cleanupLegacySupabaseAuthStorage(AGENDA_AUTH_STORAGE_KEY, ['happycash:site:auth']);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: createAdaptiveStorage(shouldPersistAgendaSession),
    persistSession: true,
    autoRefreshToken: true,
    storageKey: AGENDA_AUTH_STORAGE_KEY,
  }
});
