import React from 'react';
export type MenuTheme = Record<string, string>;
export const DEFAULT_MENU_THEME: MenuTheme = { bg:'#050b14', cardBg:'#0d1726', cardText:'#f8fafc', modalBg:'#0f172a', modalText:'#f8fafc', text:'#f1f5f9', primary:'#70e000', fontFamily:'Inter' };
export const mergeMenuTheme = (value: Partial<MenuTheme> = {}) => ({ ...DEFAULT_MENU_THEME, ...value });
export function MenuThemeProvider({ children, theme = DEFAULT_MENU_THEME }: { children: React.ReactNode; theme?: MenuTheme }) { const style = { '--menu-bg':theme.bg,'--menu-card-bg':theme.cardBg,'--menu-card-text':theme.cardText,'--menu-modal-bg':theme.modalBg,'--menu-modal-text':theme.modalText,'--menu-text':theme.text,'--menu-primary':theme.primary,'--menu-font-family':theme.fontFamily } as React.CSSProperties; return <div style={style} className="min-h-screen w-full">{children}</div>; }
export function ProductCard({ name, description, price, imageUrl, onAdd }: any) { return <article className="overflow-hidden rounded-2xl border border-white/10 bg-[var(--menu-card-bg)] text-[var(--menu-card-text)]">{imageUrl && <img src={imageUrl} alt="" className="h-32 w-full object-cover" />}<div className="p-3"><h3 className="font-semibold">{name}</h3>{description && <p className="mt-1 line-clamp-2 text-xs opacity-70">{description}</p>}<div className="mt-3 flex items-center justify-between"><span className="font-bold">R$ {Number(price).toFixed(2)}</span><button onClick={onAdd} className="rounded-lg bg-[var(--menu-primary)] px-3 py-1 text-sm font-bold text-black">+</button></div></div></article>; }
export function CategoryChip({ label, active, onClick }: any) { return <button onClick={onClick} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-sm ${active ? 'bg-[var(--menu-primary)] text-black' : 'bg-white/10 text-white'}`}>{label}</button>; }
export function SearchBar({ value, onChange, placeholder }: any) { return <input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="w-full rounded-xl border border-white/10 bg-white/10 px-4 py-3 text-white outline-none" />; }
export function QuantityStepper({ value, min = 0, onChange }: any) { return <div className="flex items-center gap-2"><button onClick={() => onChange(Math.max(min, value - 1))}>−</button><span>{value}</span><button onClick={() => onChange(value + 1)}>+</button></div>; }
export function PrimaryButton({ children, ...props }: any) { return <button {...props} className="w-full rounded-xl bg-[var(--menu-primary)] px-4 py-3 font-bold text-black disabled:opacity-40">{children}</button>; }
export function SuccessPopup({ open, title, message, closeLabel, onClose }: any) { if (!open) return null; return <div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-4"><div className="rounded-2xl bg-slate-900 p-6 text-white"><h2 className="text-xl font-bold">{title}</h2><p className="my-3 opacity-80">{message}</p><PrimaryButton onClick={onClose}>{closeLabel}</PrimaryButton></div></div>; }
