import { useEffect, useState } from 'react';
import { listApplications, decideApplication, type PartnerApplication, type DriverApplication, type ApplicationStatus } from '../lib/applications';

export default function ApplicationReviewPanel() {
  const [tab, setTab] = useState<'representantes' | 'entregadores'>('representantes');
  const [status, setStatus] = useState<ApplicationStatus | ''>('pending');
  const [reps, setReps] = useState<PartnerApplication[]>([]); const [drivers, setDrivers] = useState<DriverApplication[]>([]); const [selected, setSelected] = useState<PartnerApplication | DriverApplication | null>(null); const [error, setError] = useState('');
  const load = async () => { try { const data = await listApplications(status || undefined); setReps(data.representatives); setDrivers(data.deliveryDrivers); } catch (e) { setError(e instanceof Error ? e.message : 'Falha ao carregar.'); } };
  useEffect(() => { void load(); }, [status]);
  async function decide(kind: 'representative_applications' | 'delivery_driver_applications', id: string, next: Exclude<ApplicationStatus,'pending'|'cancelled'>) { await decideApplication(kind, id, next); setSelected(null); await load(); }
  const rows = tab === 'representantes' ? reps : drivers;
  return <section className="panel-card full-width application-review"><div className="review-heading"><div><h3>Pré-cadastros em análise</h3><p className="muted-text">Aprovação manual antes de liberar qualquer acesso.</p></div><select value={status} onChange={e => setStatus(e.target.value as ApplicationStatus | '')}><option value="pending">Em análise</option><option value="info_requested">Informações solicitadas</option><option value="approved">Aprovados</option><option value="rejected">Rejeitados</option><option value="">Todos</option></select></div><div className="review-tabs"><button className={tab==='representantes'?'active':''} onClick={()=>setTab('representantes')}>Representantes ({reps.length})</button><button className={tab==='entregadores'?'active':''} onClick={()=>setTab('entregadores')}>Entregadores ({drivers.length})</button></div>{error&&<p className="error-text">{error}</p>}<div className="review-cards">{rows.map(item=><button className="review-card" key={item.id} onClick={()=>setSelected(item)}><strong>{item.full_name}</strong><span>{item.email}</span><span>{item.city}/{item.state}</span><small>{new Date(item.created_at).toLocaleDateString('pt-BR')}</small></button>)}</div>{selected&&<div className="review-modal-backdrop" onClick={()=>setSelected(null)}><div className="review-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><h2>{selected.full_name}</h2><p>{selected.email} · {selected.phone}</p><p>{selected.city}/{selected.state} · CPF: {selected.cpf}</p>{'vehicle_type' in selected&&<p>Veículo: {selected.vehicle_type} {selected.vehicle_model || ''} {selected.vehicle_plate || ''}</p>}{'segments' in selected&&<p>Segmentos: {(selected.segments||[]).join(', ') || 'Não informado'}</p>}<div className="modal-actions"><button className="success-button" onClick={()=>void decide(tab==='representantes'?'representative_applications':'delivery_driver_applications',selected.id,'approved')}>Aprovar</button><button className="warning-button" onClick={()=>void decide(tab==='representantes'?'representative_applications':'delivery_driver_applications',selected.id,'info_requested')}>Solicitar informações</button><button className="danger-button" onClick={()=>void decide(tab==='representantes'?'representative_applications':'delivery_driver_applications',selected.id,'rejected')}>Rejeitar</button></div></div></div>}</section>;
}
